### ISSUE TITLE
Typed property Awcodes\FilamentBadgeableColumn\Components\BadgeableTagsColumn::$badges must not be accessed before initialization

### ISSUE THREAD

**Issue by ziming** [awcodes/filament-badgeable-column#14]
Hi,

I tried the code example in your readme

```php
use Awcodes\FilamentBadgeableColumn\Components\BadgeableTagsColumn;

BadgeableTagsColumn::make('tags')
    ->colors([
        'gray',
        'primary' => 'Dan',
        '#bada55' => 'Zep',
        'warning' => 'Dennis',
        '#0e7490' => 'Ryan',
    ]),
```

But I get this error

Typed property Awcodes\FilamentBadgeableColumn\Components\BadgeableTagsColumn::$badges must not be accessed before initialization

**Comment by awcodes** [comment]
What are 'tags' in your form? If there's no data then it can't match. Should still be able to default though. I'll look into it soon.

**Comment by ziming** [comment]
@awcodes tags is a relationship method. not a column on my database table.

**Comment by awcodes** [comment]
Right but it is a column on a table even if it's a relationship. It still follows Filaments naming conventions for make()

**Comment by ziming** [comment]
so what should I do to get it working?

I'm lost
