### ISSUE TITLE
separator method does not exist

### ISSUE THREAD

**Issue by mennakhalilselim** [awcodes/filament-badgeable-column#50]
### Filament Version

v3

### Plugin Version

2.x

### PHP Version

8.3

### Problem description

Method Awcodes\FilamentBadgeableColumn\Components\BadgeableColumn::seperator does not exist. 

### Expected behavior

the method is missing in HasBadges trait

### Steps to reproduce

![Screenshot from 2024-08-06 15-15-11](https://github.com/user-attachments/assets/bd55e8bd-e2d5-4fe5-9571-dc15395e6349)

**Comment by awcodes** [comment]
You spelled 'separator' wrong. There was typo in the readme. sorry. I've updated it.

Thanks.
